- import_tasks: common_tasks.yaml

- name: Activate Cgroup memory
  replace: 
    path: /boot/cmdline.txt
    regexp: '(rootwait)$'
    replace: '\1 cgroup_memory=enabled'
  notify: reboot

- name: execute handlers
  meta: flush_handlers
