ansible_python_interpreter: /usr/bin/python3
ansible_host: "{{ private_net[:-1] ~ (inventory_hostname[-1:] | int + 1) }}"
ansible_ssh_common_args: -o "ProxyCommand ssh {{ ansible_user }}@master -W %h:%p"

